server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hillel_spring
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    timeout: 60000
    url: redis://default:redispw@localhost:49153
  cache:
    type: redis